
import streamlit as st
import torch
from diffusers import StableDiffusionPipeline

st.title("AI Image Generation App")

with st.expander("About the App"):
    st.write("This is a simple image generation app that uses AI to generate images from text prompts.")

st.subheader("Image Generation using Huggingface Diffusers")

@st.cache_resource  # Cache the pipeline to avoid repeated loading
def load_pipeline():
    with torch.no_grad():
        pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
        pipe = pipe.to("cuda") if torch.cuda.is_available() else pipe.to("cpu")
        return pipe

pipe = load_pipeline()

input_prompt = st.text_input("Enter your text prompt:")

if input_prompt:
    if st.button("Generate Image"):
        with st.spinner("Generating image..."):
            try:
                image = pipe(input_prompt).images[0]
                st.image(image, caption="Generated by Huggingface Diffusers")
                st.success("Image Generated Successfully")
            except Exception as e:
                st.error(f"An error occurred: {e}")
